apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-team-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: application/deployment
    repoURL: https://github.com/itsmekrishv/platform.git
    targetRevision: HEAD
  destination:
    server: https://35.243.201.62
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true