apiVersion: devopsplatformpoc.com/v1alpha1
kind: CompositeCluster
metadata:
  name: platform-team
  labels:
    cluster-owner: sai
spec:
  compositionRef:
    name: google-k8s
  parameters:
    nodeSize: small
    minNodeCount: 1
    # namespaces:
    #   - dev
    #   - production