apiVersion: devopsplatformpoc.com/v1alpha1
kind: ClusterClaim
metadata:
  name: platform-team
spec:
  id: platform-team
  compositionSelector:
    matchLabels:
      provider: google
      cluster: gke
  parameters:
    nodeSize: small
    minNodeCount: 1
    # namespaces:
    #   - dev
    #   - production