# apiVersion: devopstoolkitseries.com/v1alpha1
# kind: ClusterClaim
# metadata:
#   name: platform-team
# spec:
#   id: platform-team
#   compositionSelector:
#     matchLabels:
#       provider: google
#       cluster: gke
#   parameters:
#     nodeSize: medium
#     minNodeCount: 1
#     namespaces:
#       - dev
#       - production
#     usage:
#       # Usage is still in `alpha` and needs to be enabled by add `--set args='{"--enable-usages"}'` to `helm install`.
#       enabled: true