apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dataload
  namespace: reltio
spec:
  components:
    - name: dataload
      properties:
        objects:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: dataload
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: dataload
              strategy:
                type: RollingUpgrade
              template:
                metadata:
                  labels:
                    app: dataload
                spec:
                  containers:
                    - image: gcr.io/customer-facing/dataload:develop
                      name: dataload
                      ports:
                        - containerPort: 80
          - apiVersion: v1
            kind: Service
            metadata:
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-type: nlb
              labels:
                app: dataload
              name: dataload
              namespace: reltio
            spec:
              externalTrafficPolicy: Local
              ports:
                - name: http
                  port: 80
                  protocol: TCP
                  targetPort: 80
              selector:
                app: dataload
              type: LoadBalancer
      type: k8s-objects
  policies:
    - name: topology-default
      type: topology
      properties:
        clusters: ['local']
        namespace: default
    - name: topology-production
      type: topology
      properties:
        clusters: ['local']
        namespace: production
  workflow:
    steps:
      - name: deploy2default
        properties:
          policies: ['topology-default']
        type: deploy
      - name: suspend
        type: suspend
      - name: deploy2production
        properties:
          policies: ['topology-production']
        type: deploy