apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-poc-k8s
  annotations:
    meta.crossplane.io/maintainers: Sai Krishna (@saikrishnav)
    meta.crossplane.io/source: github.com/itsmekrishv/platform
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational Kubernetes clusters in AWS (EKS), Google Cloud Platform (GKE), and Azure (AKS)
    meta.crossplane.io/readme: A Configuration package that defines a CompositeCluster and ClusterClaim types that can be used to create and provision Kubernetes fully operational clusters in AWS (EKS), Google Cloud Platform (GKE), and Azure (AKS).
spec:
  crossplane:
    version: '>=v1.14.0'
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-gcp-container
    version: '>=v0.33.0'
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.2.1'
  - function: xpkg.upbound.io/crossplane-contrib/function-kcl
    version: '>=v0.7.2'